apiVersion: serving.knative.dev/v1beta1
kind: Service
metadata:
  name: stream
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "1"
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
      - image: IMAGE
        ports:
        - name: h2c
          containerPort: 8080
